@echo off
echo Setting up Superheroes API...

echo Installing dependencies...
pipenv install

echo Activating virtual environment...
pipenv shell

echo Initializing database...
flask db init

echo Creating migrations...
flask db migrate -m "Initial migration"

echo Applying migrations...
flask db upgrade

echo Seeding database...
python seed.py

echo Setup complete! Run 'python app.py' to start the server.